[package]
name = "rsunimrcp_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
rsunimrcp-sys = { git = "https://github.com/akmitrich/rsunimrcp-sys" }
tokio = { version = "1", features = ["rt-multi-thread"] }
